### ISSUE TITLE
If title have 3 words => word disappear

### ISSUE THREAD

**Issue by jetaimefrc** [superbiger/vuepress-plugin-tabs#5]
I don't know why but hopefully you fix it

When having 2 words
![image](https://user-images.githubusercontent.com/24296018/71402592-e2615680-265f-11ea-95e8-4173f99d78d4.png)

When having 3 words
![image](https://user-images.githubusercontent.com/24296018/71402556-bd6ce380-265f-11ea-9833-e4cc4b159066.png)

**Comment by Magic-Doufu** [comment]
I have the same problem.
And I solved it.
check the pull-request page.

**Comment by jetaimefrc** [comment]
@superbiger Can you check PR's him?

**Comment by superbiger** [comment]
@jetaimefrc Thanks
